/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface BancorNetworkInterface extends utils.Interface {
  functions: {
    "restrictRegistryUpdate(bool)": FunctionFragment;
    "registerEtherToken(address,bool)": FunctionFragment;
    "getReturnByPath(address[],uint256)": FunctionFragment;
    "claimAndConvertFor2(address[],uint256,uint256,address,address,uint256)": FunctionFragment;
    "onlyOwnerCanUpdateRegistry()": FunctionFragment;
    "updateRegistry()": FunctionFragment;
    "convert2(address[],uint256,uint256,address,uint256)": FunctionFragment;
    "maxAffiliateFee()": FunctionFragment;
    "withdrawTokens(address,address,uint256)": FunctionFragment;
    "prevRegistry()": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "registry()": FunctionFragment;
    "rateByPath(address[],uint256)": FunctionFragment;
    "etherTokens(address)": FunctionFragment;
    "completeXConversion(address[],address,uint256,uint256,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "convertFor2(address[],uint256,uint256,address,address,uint256)": FunctionFragment;
    "claimAndConvertFor(address[],uint256,uint256,address)": FunctionFragment;
    "restoreRegistry()": FunctionFragment;
    "convertByPath(address[],uint256,uint256,address,address,uint256)": FunctionFragment;
    "xConvert(address[],uint256,uint256,bytes32,bytes32,uint256)": FunctionFragment;
    "claimAndConvert(address[],uint256,uint256)": FunctionFragment;
    "convertFor(address[],uint256,uint256,address)": FunctionFragment;
    "xConvert2(address[],uint256,uint256,bytes32,bytes32,uint256,address,uint256)": FunctionFragment;
    "newOwner()": FunctionFragment;
    "conversionPath(address,address)": FunctionFragment;
    "claimAndConvert2(address[],uint256,uint256,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "convert(address[],uint256,uint256)": FunctionFragment;
    "setMaxAffiliateFee(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "restrictRegistryUpdate",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEtherToken",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getReturnByPath",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAndConvertFor2",
    values: [string[], BigNumberish, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onlyOwnerCanUpdateRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convert2",
    values: [string[], BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxAffiliateFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prevRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateByPath",
    values: [string[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "etherTokens", values: [string]): string;
  encodeFunctionData(
    functionFragment: "completeXConversion",
    values: [string[], string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "convertFor2",
    values: [string[], BigNumberish, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAndConvertFor",
    values: [string[], BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "restoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convertByPath",
    values: [string[], BigNumberish, BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xConvert",
    values: [
      string[],
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAndConvert",
    values: [string[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertFor",
    values: [string[], BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "xConvert2",
    values: [
      string[],
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "newOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "conversionPath",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAndConvert2",
    values: [string[], BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "convert",
    values: [string[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAffiliateFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "restrictRegistryUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEtherToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReturnByPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAndConvertFor2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onlyOwnerCanUpdateRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "convert2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxAffiliateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prevRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rateByPath", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "etherTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeXConversion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertFor2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAndConvertFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertByPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xConvert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimAndConvert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "convertFor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xConvert2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "conversionPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAndConvert2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "convert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAffiliateFee",
    data: BytesLike
  ): Result;

  events: {
    "Conversion(address,address,address,uint256,uint256,address)": EventFragment;
    "OwnerUpdate(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Conversion"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdate"): EventFragment;
}

export type ConversionEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string],
  {
    _smartToken: string;
    _fromToken: string;
    _toToken: string;
    _fromAmount: BigNumber;
    _toAmount: BigNumber;
    _trader: string;
  }
>;

export type ConversionEventFilter = TypedEventFilter<ConversionEvent>;

export type OwnerUpdateEvent = TypedEvent<
  [string, string],
  { _prevOwner: string; _newOwner: string }
>;

export type OwnerUpdateEventFilter = TypedEventFilter<OwnerUpdateEvent>;

export interface BancorNetwork extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BancorNetworkInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerEtherToken(
      _token: string,
      _register: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getReturnByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    claimAndConvertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<[boolean]>;

    updateRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    convert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxAffiliateFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawTokens(
      _token: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    prevRegistry(overrides?: CallOverrides): Promise<[string]>;

    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    rateByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    etherTokens(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    completeXConversion(
      _path: string[],
      _bancorX: string,
      _conversionId: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    convertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimAndConvertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    restoreRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    convertByPath(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    xConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimAndConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    convertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    xConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newOwner(overrides?: CallOverrides): Promise<[string]>;

    conversionPath(
      _sourceToken: string,
      _targetToken: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    claimAndConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    convert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxAffiliateFee(
      _maxAffiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  restrictRegistryUpdate(
    _onlyOwnerCanUpdateRegistry: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerEtherToken(
    _token: string,
    _register: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getReturnByPath(
    _path: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  claimAndConvertFor2(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _beneficiary: string,
    _affiliateAccount: string,
    _affiliateFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<boolean>;

  updateRegistry(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  convert2(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _affiliateAccount: string,
    _affiliateFee: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxAffiliateFee(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawTokens(
    _token: string,
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  prevRegistry(overrides?: CallOverrides): Promise<string>;

  acceptOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registry(overrides?: CallOverrides): Promise<string>;

  rateByPath(
    _path: string[],
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  etherTokens(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  completeXConversion(
    _path: string[],
    _bancorX: string,
    _conversionId: BigNumberish,
    _minReturn: BigNumberish,
    _beneficiary: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  convertFor2(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _beneficiary: string,
    _affiliateAccount: string,
    _affiliateFee: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimAndConvertFor(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _beneficiary: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  restoreRegistry(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  convertByPath(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _beneficiary: string,
    _affiliateAccount: string,
    _affiliateFee: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  xConvert(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _targetBlockchain: BytesLike,
    _targetAccount: BytesLike,
    _conversionId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimAndConvert(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  convertFor(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _beneficiary: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  xConvert2(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _targetBlockchain: BytesLike,
    _targetAccount: BytesLike,
    _conversionId: BigNumberish,
    _affiliateAccount: string,
    _affiliateFee: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newOwner(overrides?: CallOverrides): Promise<string>;

  conversionPath(
    _sourceToken: string,
    _targetToken: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  claimAndConvert2(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    _affiliateAccount: string,
    _affiliateFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  convert(
    _path: string[],
    _amount: BigNumberish,
    _minReturn: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxAffiliateFee(
    _maxAffiliateFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    registerEtherToken(
      _token: string,
      _register: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    getReturnByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    claimAndConvertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<boolean>;

    updateRegistry(overrides?: CallOverrides): Promise<void>;

    convert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxAffiliateFee(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawTokens(
      _token: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    prevRegistry(overrides?: CallOverrides): Promise<string>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    registry(overrides?: CallOverrides): Promise<string>;

    rateByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    etherTokens(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    completeXConversion(
      _path: string[],
      _bancorX: string,
      _conversionId: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    convertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAndConvertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    restoreRegistry(overrides?: CallOverrides): Promise<void>;

    convertByPath(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    xConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAndConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    xConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newOwner(overrides?: CallOverrides): Promise<string>;

    conversionPath(
      _sourceToken: string,
      _targetToken: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    claimAndConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    convert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setMaxAffiliateFee(
      _maxAffiliateFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Conversion(address,address,address,uint256,uint256,address)"(
      _smartToken?: string | null,
      _fromToken?: string | null,
      _toToken?: string | null,
      _fromAmount?: null,
      _toAmount?: null,
      _trader?: null
    ): ConversionEventFilter;
    Conversion(
      _smartToken?: string | null,
      _fromToken?: string | null,
      _toToken?: string | null,
      _fromAmount?: null,
      _toAmount?: null,
      _trader?: null
    ): ConversionEventFilter;

    "OwnerUpdate(address,address)"(
      _prevOwner?: string | null,
      _newOwner?: string | null
    ): OwnerUpdateEventFilter;
    OwnerUpdate(
      _prevOwner?: string | null,
      _newOwner?: string | null
    ): OwnerUpdateEventFilter;
  };

  estimateGas: {
    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerEtherToken(
      _token: string,
      _register: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getReturnByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAndConvertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    updateRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    convert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxAffiliateFee(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawTokens(
      _token: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    prevRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    rateByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    etherTokens(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    completeXConversion(
      _path: string[],
      _bancorX: string,
      _conversionId: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    convertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimAndConvertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    restoreRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    convertByPath(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    xConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimAndConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    convertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    xConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newOwner(overrides?: CallOverrides): Promise<BigNumber>;

    conversionPath(
      _sourceToken: string,
      _targetToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimAndConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    convert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxAffiliateFee(
      _maxAffiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerEtherToken(
      _token: string,
      _register: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getReturnByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimAndConvertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onlyOwnerCanUpdateRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    convert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxAffiliateFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawTokens(
      _token: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    prevRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rateByPath(
      _path: string[],
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    etherTokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    completeXConversion(
      _path: string[],
      _bancorX: string,
      _conversionId: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    convertFor2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimAndConvertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    restoreRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    convertByPath(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    xConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimAndConvert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    convertFor(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _beneficiary: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    xConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _targetBlockchain: BytesLike,
      _targetAccount: BytesLike,
      _conversionId: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    conversionPath(
      _sourceToken: string,
      _targetToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimAndConvert2(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      _affiliateAccount: string,
      _affiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    convert(
      _path: string[],
      _amount: BigNumberish,
      _minReturn: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxAffiliateFee(
      _maxAffiliateFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
