/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ConverterRegistryInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "addConverter(address)": FunctionFragment;
    "getAnchor(uint256)": FunctionFragment;
    "getAnchorCount()": FunctionFragment;
    "getAnchors()": FunctionFragment;
    "getConvertersByAnchors(address[])": FunctionFragment;
    "getConvertersBySmartTokens(address[])": FunctionFragment;
    "getConvertibleToken(uint256)": FunctionFragment;
    "getConvertibleTokenAnchor(address,uint256)": FunctionFragment;
    "getConvertibleTokenAnchorCount(address)": FunctionFragment;
    "getConvertibleTokenAnchors(address)": FunctionFragment;
    "getConvertibleTokenCount()": FunctionFragment;
    "getConvertibleTokenSmartToken(address,uint256)": FunctionFragment;
    "getConvertibleTokenSmartTokenCount(address)": FunctionFragment;
    "getConvertibleTokenSmartTokens(address)": FunctionFragment;
    "getConvertibleTokens()": FunctionFragment;
    "getLiquidityPool(uint256)": FunctionFragment;
    "getLiquidityPoolByConfig(uint16,address[],uint32[])": FunctionFragment;
    "getLiquidityPoolByReserveConfig(address[],uint32[])": FunctionFragment;
    "getLiquidityPoolCount()": FunctionFragment;
    "getLiquidityPools()": FunctionFragment;
    "getSmartToken(uint256)": FunctionFragment;
    "getSmartTokenCount()": FunctionFragment;
    "getSmartTokens()": FunctionFragment;
    "isAnchor(address)": FunctionFragment;
    "isConverterValid(address)": FunctionFragment;
    "isConvertibleToken(address)": FunctionFragment;
    "isConvertibleTokenAnchor(address,address)": FunctionFragment;
    "isConvertibleTokenSmartToken(address,address)": FunctionFragment;
    "isLiquidityPool(address)": FunctionFragment;
    "isSimilarLiquidityPoolRegistered(address)": FunctionFragment;
    "isSmartToken(address)": FunctionFragment;
    "newConverter(uint16,string,string,uint8,uint32,address[],uint32[])": FunctionFragment;
    "newOwner()": FunctionFragment;
    "onlyOwnerCanUpdateRegistry()": FunctionFragment;
    "owner()": FunctionFragment;
    "prevRegistry()": FunctionFragment;
    "registry()": FunctionFragment;
    "removeConverter(address)": FunctionFragment;
    "restoreRegistry()": FunctionFragment;
    "restrictRegistryUpdate(bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateRegistry()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addConverter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAnchors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertersByAnchors",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertersBySmartTokens",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenAnchor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenAnchorCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenAnchors",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenSmartToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenSmartTokenCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokenSmartTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConvertibleTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityPoolByConfig",
    values: [BigNumberish, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityPoolByReserveConfig",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSmartToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSmartTokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSmartTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isAnchor", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isConverterValid",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isConvertibleToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isConvertibleTokenAnchor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isConvertibleTokenSmartToken",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isLiquidityPool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isSimilarLiquidityPoolRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isSmartToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "newConverter",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      string[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "newOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onlyOwnerCanUpdateRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "prevRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeConverter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "restoreRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "restrictRegistryUpdate",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addConverter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAnchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAnchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAnchors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConvertersByAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertersBySmartTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenAnchorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenSmartToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenSmartTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokenSmartTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConvertibleTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityPoolByConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityPoolByReserveConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmartToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmartTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmartTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAnchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isConverterValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConvertibleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConvertibleTokenAnchor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConvertibleTokenSmartToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLiquidityPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSimilarLiquidityPoolRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSmartToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newConverter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onlyOwnerCanUpdateRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prevRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeConverter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restoreRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictRegistryUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRegistry",
    data: BytesLike
  ): Result;

  events: {
    "ConverterAnchorAdded(address)": EventFragment;
    "ConverterAnchorRemoved(address)": EventFragment;
    "ConvertibleTokenAdded(address,address)": EventFragment;
    "ConvertibleTokenRemoved(address,address)": EventFragment;
    "LiquidityPoolAdded(address)": EventFragment;
    "LiquidityPoolRemoved(address)": EventFragment;
    "OwnerUpdate(address,address)": EventFragment;
    "SmartTokenAdded(address)": EventFragment;
    "SmartTokenRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConverterAnchorAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConverterAnchorRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConvertibleTokenAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConvertibleTokenRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidityPoolAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidityPoolRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SmartTokenAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SmartTokenRemoved"): EventFragment;
}

export type ConverterAnchorAddedEvent = TypedEvent<
  [string],
  { _anchor: string }
>;

export type ConverterAnchorAddedEventFilter =
  TypedEventFilter<ConverterAnchorAddedEvent>;

export type ConverterAnchorRemovedEvent = TypedEvent<
  [string],
  { _anchor: string }
>;

export type ConverterAnchorRemovedEventFilter =
  TypedEventFilter<ConverterAnchorRemovedEvent>;

export type ConvertibleTokenAddedEvent = TypedEvent<
  [string, string],
  { _convertibleToken: string; _smartToken: string }
>;

export type ConvertibleTokenAddedEventFilter =
  TypedEventFilter<ConvertibleTokenAddedEvent>;

export type ConvertibleTokenRemovedEvent = TypedEvent<
  [string, string],
  { _convertibleToken: string; _smartToken: string }
>;

export type ConvertibleTokenRemovedEventFilter =
  TypedEventFilter<ConvertibleTokenRemovedEvent>;

export type LiquidityPoolAddedEvent = TypedEvent<
  [string],
  { _liquidityPool: string }
>;

export type LiquidityPoolAddedEventFilter =
  TypedEventFilter<LiquidityPoolAddedEvent>;

export type LiquidityPoolRemovedEvent = TypedEvent<
  [string],
  { _liquidityPool: string }
>;

export type LiquidityPoolRemovedEventFilter =
  TypedEventFilter<LiquidityPoolRemovedEvent>;

export type OwnerUpdateEvent = TypedEvent<
  [string, string],
  { _prevOwner: string; _newOwner: string }
>;

export type OwnerUpdateEventFilter = TypedEventFilter<OwnerUpdateEvent>;

export type SmartTokenAddedEvent = TypedEvent<
  [string],
  { _smartToken: string }
>;

export type SmartTokenAddedEventFilter = TypedEventFilter<SmartTokenAddedEvent>;

export type SmartTokenRemovedEvent = TypedEvent<
  [string],
  { _smartToken: string }
>;

export type SmartTokenRemovedEventFilter =
  TypedEventFilter<SmartTokenRemovedEvent>;

export interface ConverterRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConverterRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addConverter(
      _converter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAnchor(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getAnchorCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAnchors(overrides?: CallOverrides): Promise<[string[]]>;

    getConvertersByAnchors(
      _anchors: string[],
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getConvertersBySmartTokens(
      _smartTokens: string[],
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getConvertibleToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getConvertibleTokenAnchor(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getConvertibleTokenAnchorCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getConvertibleTokenAnchors(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getConvertibleTokenCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getConvertibleTokenSmartToken(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getConvertibleTokenSmartTokenCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getConvertibleTokenSmartTokens(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getConvertibleTokens(overrides?: CallOverrides): Promise<[string[]]>;

    getLiquidityPool(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getLiquidityPoolByConfig(
      _type: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    getLiquidityPoolByReserveConfig(
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    getLiquidityPoolCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLiquidityPools(overrides?: CallOverrides): Promise<[string[]]>;

    getSmartToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSmartTokenCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSmartTokens(overrides?: CallOverrides): Promise<[string[]]>;

    isAnchor(_value: string, overrides?: CallOverrides): Promise<[boolean]>;

    isConverterValid(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isConvertibleToken(
      _value: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isConvertibleTokenAnchor(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isConvertibleTokenSmartToken(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isLiquidityPool(
      _value: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSimilarLiquidityPoolRegistered(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isSmartToken(_value: string, overrides?: CallOverrides): Promise<[boolean]>;

    newConverter(
      _type: BigNumberish,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _maxConversionFee: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    newOwner(overrides?: CallOverrides): Promise<[string]>;

    onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    prevRegistry(overrides?: CallOverrides): Promise<[string]>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    removeConverter(
      _converter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    restoreRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addConverter(
    _converter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAnchor(_index: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getAnchorCount(overrides?: CallOverrides): Promise<BigNumber>;

  getAnchors(overrides?: CallOverrides): Promise<string[]>;

  getConvertersByAnchors(
    _anchors: string[],
    overrides?: CallOverrides
  ): Promise<string[]>;

  getConvertersBySmartTokens(
    _smartTokens: string[],
    overrides?: CallOverrides
  ): Promise<string[]>;

  getConvertibleToken(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getConvertibleTokenAnchor(
    _convertibleToken: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getConvertibleTokenAnchorCount(
    _convertibleToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getConvertibleTokenAnchors(
    _convertibleToken: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getConvertibleTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

  getConvertibleTokenSmartToken(
    _convertibleToken: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getConvertibleTokenSmartTokenCount(
    _convertibleToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getConvertibleTokenSmartTokens(
    _convertibleToken: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getConvertibleTokens(overrides?: CallOverrides): Promise<string[]>;

  getLiquidityPool(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getLiquidityPoolByConfig(
    _type: BigNumberish,
    _reserveTokens: string[],
    _reserveWeights: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<string>;

  getLiquidityPoolByReserveConfig(
    _reserveTokens: string[],
    _reserveWeights: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<string>;

  getLiquidityPoolCount(overrides?: CallOverrides): Promise<BigNumber>;

  getLiquidityPools(overrides?: CallOverrides): Promise<string[]>;

  getSmartToken(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getSmartTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

  getSmartTokens(overrides?: CallOverrides): Promise<string[]>;

  isAnchor(_value: string, overrides?: CallOverrides): Promise<boolean>;

  isConverterValid(
    _converter: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isConvertibleToken(
    _value: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isConvertibleTokenAnchor(
    _convertibleToken: string,
    _value: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isConvertibleTokenSmartToken(
    _convertibleToken: string,
    _value: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isLiquidityPool(_value: string, overrides?: CallOverrides): Promise<boolean>;

  isSimilarLiquidityPoolRegistered(
    _converter: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isSmartToken(_value: string, overrides?: CallOverrides): Promise<boolean>;

  newConverter(
    _type: BigNumberish,
    _name: string,
    _symbol: string,
    _decimals: BigNumberish,
    _maxConversionFee: BigNumberish,
    _reserveTokens: string[],
    _reserveWeights: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  newOwner(overrides?: CallOverrides): Promise<string>;

  onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  prevRegistry(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  removeConverter(
    _converter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  restoreRegistry(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  restrictRegistryUpdate(
    _onlyOwnerCanUpdateRegistry: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRegistry(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    addConverter(_converter: string, overrides?: CallOverrides): Promise<void>;

    getAnchor(_index: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getAnchorCount(overrides?: CallOverrides): Promise<BigNumber>;

    getAnchors(overrides?: CallOverrides): Promise<string[]>;

    getConvertersByAnchors(
      _anchors: string[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    getConvertersBySmartTokens(
      _smartTokens: string[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    getConvertibleToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getConvertibleTokenAnchor(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getConvertibleTokenAnchorCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenAnchors(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getConvertibleTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    getConvertibleTokenSmartToken(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getConvertibleTokenSmartTokenCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenSmartTokens(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getConvertibleTokens(overrides?: CallOverrides): Promise<string[]>;

    getLiquidityPool(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getLiquidityPoolByConfig(
      _type: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    getLiquidityPoolByReserveConfig(
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    getLiquidityPoolCount(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityPools(overrides?: CallOverrides): Promise<string[]>;

    getSmartToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getSmartTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    getSmartTokens(overrides?: CallOverrides): Promise<string[]>;

    isAnchor(_value: string, overrides?: CallOverrides): Promise<boolean>;

    isConverterValid(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isConvertibleToken(
      _value: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isConvertibleTokenAnchor(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isConvertibleTokenSmartToken(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isLiquidityPool(
      _value: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSimilarLiquidityPoolRegistered(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isSmartToken(_value: string, overrides?: CallOverrides): Promise<boolean>;

    newConverter(
      _type: BigNumberish,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _maxConversionFee: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    newOwner(overrides?: CallOverrides): Promise<string>;

    onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    prevRegistry(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    removeConverter(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    restoreRegistry(overrides?: CallOverrides): Promise<void>;

    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRegistry(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ConverterAnchorAdded(address)"(
      _anchor?: string | null
    ): ConverterAnchorAddedEventFilter;
    ConverterAnchorAdded(
      _anchor?: string | null
    ): ConverterAnchorAddedEventFilter;

    "ConverterAnchorRemoved(address)"(
      _anchor?: string | null
    ): ConverterAnchorRemovedEventFilter;
    ConverterAnchorRemoved(
      _anchor?: string | null
    ): ConverterAnchorRemovedEventFilter;

    "ConvertibleTokenAdded(address,address)"(
      _convertibleToken?: string | null,
      _smartToken?: string | null
    ): ConvertibleTokenAddedEventFilter;
    ConvertibleTokenAdded(
      _convertibleToken?: string | null,
      _smartToken?: string | null
    ): ConvertibleTokenAddedEventFilter;

    "ConvertibleTokenRemoved(address,address)"(
      _convertibleToken?: string | null,
      _smartToken?: string | null
    ): ConvertibleTokenRemovedEventFilter;
    ConvertibleTokenRemoved(
      _convertibleToken?: string | null,
      _smartToken?: string | null
    ): ConvertibleTokenRemovedEventFilter;

    "LiquidityPoolAdded(address)"(
      _liquidityPool?: string | null
    ): LiquidityPoolAddedEventFilter;
    LiquidityPoolAdded(
      _liquidityPool?: string | null
    ): LiquidityPoolAddedEventFilter;

    "LiquidityPoolRemoved(address)"(
      _liquidityPool?: string | null
    ): LiquidityPoolRemovedEventFilter;
    LiquidityPoolRemoved(
      _liquidityPool?: string | null
    ): LiquidityPoolRemovedEventFilter;

    "OwnerUpdate(address,address)"(
      _prevOwner?: string | null,
      _newOwner?: string | null
    ): OwnerUpdateEventFilter;
    OwnerUpdate(
      _prevOwner?: string | null,
      _newOwner?: string | null
    ): OwnerUpdateEventFilter;

    "SmartTokenAdded(address)"(
      _smartToken?: string | null
    ): SmartTokenAddedEventFilter;
    SmartTokenAdded(_smartToken?: string | null): SmartTokenAddedEventFilter;

    "SmartTokenRemoved(address)"(
      _smartToken?: string | null
    ): SmartTokenRemovedEventFilter;
    SmartTokenRemoved(
      _smartToken?: string | null
    ): SmartTokenRemovedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addConverter(
      _converter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAnchor(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAnchorCount(overrides?: CallOverrides): Promise<BigNumber>;

    getAnchors(overrides?: CallOverrides): Promise<BigNumber>;

    getConvertersByAnchors(
      _anchors: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertersBySmartTokens(
      _smartTokens: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenAnchor(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenAnchorCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenAnchors(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    getConvertibleTokenSmartToken(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenSmartTokenCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokenSmartTokens(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConvertibleTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityPool(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidityPoolByConfig(
      _type: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidityPoolByReserveConfig(
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLiquidityPoolCount(overrides?: CallOverrides): Promise<BigNumber>;

    getLiquidityPools(overrides?: CallOverrides): Promise<BigNumber>;

    getSmartToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSmartTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    getSmartTokens(overrides?: CallOverrides): Promise<BigNumber>;

    isAnchor(_value: string, overrides?: CallOverrides): Promise<BigNumber>;

    isConverterValid(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isConvertibleToken(
      _value: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isConvertibleTokenAnchor(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isConvertibleTokenSmartToken(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isLiquidityPool(
      _value: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSimilarLiquidityPoolRegistered(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isSmartToken(_value: string, overrides?: CallOverrides): Promise<BigNumber>;

    newConverter(
      _type: BigNumberish,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _maxConversionFee: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    newOwner(overrides?: CallOverrides): Promise<BigNumber>;

    onlyOwnerCanUpdateRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    prevRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    removeConverter(
      _converter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    restoreRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addConverter(
      _converter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAnchor(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAnchorCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAnchors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getConvertersByAnchors(
      _anchors: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertersBySmartTokens(
      _smartTokens: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenAnchor(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenAnchorCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenAnchors(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenSmartToken(
      _convertibleToken: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenSmartTokenCount(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokenSmartTokens(
      _convertibleToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConvertibleTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityPool(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityPoolByConfig(
      _type: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityPoolByReserveConfig(
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityPoolCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLiquidityPools(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSmartToken(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSmartTokenCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSmartTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAnchor(
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConverterValid(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConvertibleToken(
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConvertibleTokenAnchor(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isConvertibleTokenSmartToken(
      _convertibleToken: string,
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isLiquidityPool(
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSimilarLiquidityPoolRegistered(
      _converter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSmartToken(
      _value: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newConverter(
      _type: BigNumberish,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _maxConversionFee: BigNumberish,
      _reserveTokens: string[],
      _reserveWeights: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    newOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onlyOwnerCanUpdateRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    prevRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeConverter(
      _converter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    restoreRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    restrictRegistryUpdate(
      _onlyOwnerCanUpdateRegistry: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRegistry(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
